<html>
    <head>
        <link rel=stylesheet href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/base/jquery-ui.css" />
        <link rel=stylesheet href="/css/style.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
        <script src="/js/vh.js"></script>
    </head>
    <body>
        <div class="layout">
            <div class="header">

            </div>
            <div id="content" style="height:700px">
                <% content %>
            </div>
            <div id="footer" classe ="footer">
                Vo2 Lab - © 2011
            </div>
        </div>
    </body>
</html>